# Generated by Django 3.1.4 on 2020-12-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_festivalurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalurl',
            name='siteUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
